"""Filter DSL reference for Amazing Marvin SmartLists.

Mirrors the predicate, operator, and token vocabulary used by Marvin's
advanced filter engine. The Marvin help center documents a subset:
https://help.amazingmarvin.com/en/articles/2070779-advanced-smart-list-filters

Used by the SmartLists schema in doc_types.py to give MCP callers a complete
operator inventory when reading or writing smart-list filter expressions.

Aliases: predicates carrying a ``*`` prefix in user-facing syntax (e.g.
``*backburner``, ``*new``, ``*stale``, ``*review``, ``*reward``,
``*hasSubtasks``, ``*hasOpenSubtasks``, ``*minutesTracked``, ``*rewardPoints``,
``*viaEmail``, ``*inGoal``) are accepted with or without the prefix.
"""

# Predicates from the advanced filter DSL. Mix of boolean tests (return
# True/False), comparable fields (return numeric/date values), and date
# keywords (return absolute or relative dates). Sorted alphabetically.
PREDICATES: dict[str, str] = {
    "backburner": "True if this task/project is on the backburner.",
    "createdRecently": "True if this task/project was created in the last 7 days.",
    "createdThisWeek": "True if this task/project was created this week.",
    "createdToday": "True if this task/project was created today.",
    "creationDate": "The date when the task/project was created.",
    "doneDate": "The date when the task/project was marked as complete. Only works in Search, as completed items are not shown in Smart Lists.",
    "dueDate": "The task/project's due date. This includes inheritance.",
    "dueIn3Days": "True if this task/project is due within the next 3 days.",
    "dueIn7Days": "True if this task/project is due within the next 7 days.",
    "dueThisWeek": "True if this task/project is due this week.",
    "dueToday": "True if this task/project is due today.",
    "dueTomorrow": "True if this task/project is due tomorrow.",
    "endDate": "The task/project's end date.",
    "endOfMonth": "The date of the last day of this month.",
    "endOfWeek": "The date of the end of the work week. This respects your work week settings.",
    "firstScheduled": "The task/project's first schedule date. This can help you determine whether you procrastinated it, and how long ago.",
    "fromPinned": "True if this task was created from a pinned task.",
    "hasBeenScheduled": "True if this task/project was scheduled in the past, or false if it's never been scheduled. If it was scheduled in the past, then this is a good indicator that you've procrastinated!",
    "hasChildren": "True if this project has open tasks or subprojects.",
    "hasDependants": "True if this task/project is a dependency of an open task/project.",
    "hasEnergy": "True if this task/project has an energy type set.",
    "hasGoal": "True if this task/project is linked to a goal.",
    "hasNote": "True if this task/project has a note.",
    "hasOpenSubtasks": "Matches Tasks that have open Subtasks.",
    "hasPledge": "True if this task/project has a pledge date.",
    "hasReminder": "True if the task has a reminder time in the future.",
    "hasReviewDate": "True if this task/project has a review date.",
    "hasStartDate": "True if this task/project has a start date.",
    "hasSubtasks": "Matches Tasks that have Subtasks.",
    "hasTime": "True if this task/project has a time in its title (using any time format, like 7am or 19:00).",
    "inCurrentTimeBlock": "True if this task/project matches the current time block's linked smart list.",
    "inFroggedProject": "True if this task is in a frogged/dreaded project.",
    "inGoal": "Matches Tasks/Projects that are in any Goal.",
    "inheritedScheduleDate": "The task/project's inherited schedule date. This is the minimum of the schedule dates of the item and its ancestors, or null if none are scheduled.",
    "inImportantProject": "True if this task is in a starred/important project.",
    "inMIPProject": "True if this task is in a Most Important Project.",
    "isCalDAVSynced": "True if this task is synced to a CalDAV provider.",
    "isCalendarSynced": "True if this task is synced to a calendar.",
    "isCategory": "True if this is a category (not a project or task).",
    "isDependent": "True if this task/project is dependent on an open task/project.",
    "isFirstStep": "True if this task is the first step of a project.",
    "isFirstUnscheduled": "True if this task is the first unscheduled task in a project.",
    "isGoogleSynced": "True if this task is synced to a google calendar.",
    "isHabit": "True if this is a habit.",
    "isIcloudSynced": "True if this task is synced to an iCloud calendar.",
    "isNextStep": "True if this task is the next step of a project.",
    "isOutlookSynced": "True if this task is synced to an outlook calendar.",
    "isParallel": "Matches non-sequential projects.",
    "isPinned": "True if this task is itself pinned (i.e. the pinned task parent that lives in the Master List).",
    "isPledged": "True if this task/project has a future scheduleDate.",
    "isRecurring": "True if this task/project was created from a recurring item.",
    "isScheduled": "True if this task/project is currently scheduled.",
    "isSequential": "Matches sequential projects.",
    "isShared": "True if this task is in a shared list.",
    "isSnoozed": "True if this task/project has been snoozed.",
    "isStarred": "True if this has importance (any star). Does NOT include low priority (down arrow).",
    "isTracked": "True if this task has been time tracked.",
    "isTracking": "Experimental. True if the task is being tracked.",
    "isUnscheduled": "True if the task/project isn't scheduled, else false if is.",
    "isUrgent": "True if this task/project has any urgency level.",
    "isWorkSession": "Matches Work Session tasks.",
    "isYahooSynced": "True if this task is synced to a yahoo calendar.",
    "justStarted": "True if this item left the backburner due to its start date and you haven't yet acknowledged it, or false otherwise (i.e. it wasn't just started or you already acknowledged it).",
    "longTask": "True if this task/project has a duration over 1 hour.",
    "minutesTracked": "The number of minutes tracked on this task, else 0.",
    "mip": "True if this is a MIP project.",
    "missingNextStep": "True if this project doesn't have any next steps (i.e. open tasks).",
    "neverProcrastinated": "True if this task/project has never been rescheduled.",
    "neverScheduled": "True if this task/project has never been scheduled.",
    "new": "True if this task/project is newly available for working on (due to dependencies, start date, or newly created recurring projects).",
    "noGoal": "True if this task/project is not linked to a goal.",
    "noPledge": "True if this task/project does not have a pledge date.",
    "noReviewDate": "True if this task/project does not have a review date.",
    "noStartDate": "True if this task/project does not have a start date.",
    "noTimeEstimate": "True if this task/project does not have a duration.",
    "notStarted": "True if this task/project has a future start date.",
    "now": "True if this task is scheduled for right now.",
    "numDoneTasks": "The number of completed tasks in this project, or null if it's a task.",
    "numLabels": "The number of labels this task/project has.",
    "numOpenSubtasks": "The number of open Subtasks a Task has.",
    "numOpenTasks": "The number of open tasks in this project, or null if it's a task.",
    "numScheduledTasks": "The number of scheduled open tasks in this project, or null if it's a task.",
    "numSubtasks": "The number of Subtasks a Task has (open and completed).",
    "numUnscheduledTasks": "The number of unscheduled open tasks in this project, or null if it's a task.",
    "orbit": "True if this task/project is in orbit.",
    "pickedProject": "True if this is a project that has been picked today using the Project Focus Picker, or false if it's not a project or hasn't been picked.",
    "plannedMonth": "The task/project's planned month. This is null if not planned.",
    "plannedWeek": "The task/project's planned week. This is actually the date of the first day of that week, or null if not planned.",
    "pledgeDate": "The task/project's accountability pledge date.",
    "pledgeDue1Day": "True if this task/project has a pledge due tomorrow.",
    "pledgeDue3Days": "True if this task/project has a pledge due within 3 days.",
    "pledgeDue7Days": "True if this task/project has a pledge due within 7 days.",
    "pledgeDueToday": "True if this task/project has a pledge due today.",
    "previouslyScheduled": "True if this task/project was scheduled in the past.",
    "procrastinated": "True if this task/project has been rescheduled (procrastinated).",
    "procrastinationCount": "The number of days this task/project has been procrastinated.",
    "quickTask": "True if this task/project has a duration under 15 minutes.",
    "review": "True if it's time to review this task/project.",
    "reviewDate": "The task/project's review date.",
    "reviewIn3Days": "True if this task/project is due for review within the next 3 days.",
    "reviewIn7Days": "True if this task/project is due for review within the next 7 days.",
    "reviewOverdue": "True if this task/project is past its review date.",
    "reviewThisWeek": "True if this task/project is due for review this week.",
    "reviewToday": "True if this task/project is due for review today.",
    "reviewTomorrow": "True if this task/project is due for review tomorrow.",
    "reward": "True if this is a reward task (from the Reward Tasks strategy). Note: this is not the same as having an attached reward (from the Rewards strategy).",
    "rewardPoints": "The number of reward points this task/project has been directly assigned (not including defaults!).",
    "scheduleDate": "The task/project's schedule date. This does not include inheritance! So if a task is not scheduled, but its parent project is, this is null instead.",
    "scheduleDatePlain": "The task/project's schedule date ignoring rollover, auto-schedule due tasks, and inheritance.",
    "scheduleWeek": "The week when the task/project is scheduled onto the stack. This is actually the date of the first day of that week, or null if unscheduled.",
    "selectedDate": "The main view's selected date. This is the date that is shown in the sidebar, not today. You can change it using arrow keys (or buttons in the sidebar) to look at your schedule in the future/past in My Day.",
    "selectedMonth": "The main view's selected date's month. Useful e.g. for comparing with &plannedMonth.",
    "selectedWeek": "The main view's selected date's start of week date. Useful e.g. for comparing with &plannedWeek. Warning: Monday is considered the start of the week here!",
    "stale": "True if this task/project matches your Staleness Warning conditions.",
    "startDate": "The task/project's start date.",
    "started": "True if this task/project has a start date in the past.",
    "startOfISOWeek": "The date of the start of the work week. This uses Monday as the week start and doesn't respect your work week settings. This can be helpful for working with *plannedWeek since planned weeks in Marvin are always based on ISO weeks.",
    "startOfMonth": "The date of the 1st day of this month.",
    "startOfWeek": "The date of the start of the work week. This respects your work week settings.",
    "startsIn3Days": "True if this task/project starts within the next 3 days.",
    "startsIn7Days": "True if this task/project starts within the next 7 days.",
    "startsThisWeek": "True if this task/project starts this week.",
    "startsToday": "True if this task/project starts today.",
    "startsTomorrow": "True if this task/project starts tomorrow.",
    "time": "The task/project's time (extracted from its title). Useful for comparing with a fixed time.",
    "today": "Today's date.",
    "tomorrow": "Tomorrow's date.",
    "viaEmail": "Matches Tasks that were created by email.",
    "workTomorrow": "Tomorrow's date, but skipping weekends. So today is Friday and your weekends are Saturday+Sunday, this is Monday's date. This respects your work week settings.",
    "yesterday": "Yesterday's date.",
}

# Functions accepting a sub-expression as their argument.
FUNCTIONS: dict[str, str] = {
    "parent": "Match items whose parent matches the given expression. e.g. parent(*isStarred type:project &&) matches tasks inside starred projects.",
    "anyAncestor": "Match items where any ancestor (parent, grandparent, ...) matches the expression.",
    "anyChild": "Match items that have at least one child matching the expression.",
    "allChildren": "Match items where every child matches the expression.",
    "anySibling": "Match items where any sibling matches the expression.",
    "allSiblings": "Match items where every sibling matches the expression.",
}

# Postfix (RPN) operators. Operands appear before the operator.
OPERATORS: dict[str, str] = {
    "||": "OR (logical disjunction).",
    "&&": "AND (logical conjunction).",
    "!": "NOT (unary negation).",
    "==": "Equality.",
    "!=": "Inequality.",
    ">": "Greater than.",
    "<": "Less than.",
    ">=": "Greater than or equal.",
    "<=": "Less than or equal.",
    "+": "Addition (arithmetic).",
    "-": "Subtraction (arithmetic).",
}

# Token types recognized by the DSL parser. Plus implicit prefix tokens:
# @label / @"label name" — label reference;
# `type:task|project|category` — type filter.
# (Backticks are load-bearing: a comment starting with `# type:` is read as a
# PEP 484 type comment and fails to parse.)
TOKENS: dict[str, str] = {
    "number": "Integer literal (regex: ^[0-9]+$). Use for comparing rewardPoints, numScheduledTasks, etc.",
    "float": "Decimal literal (regex: ^[0-9]+\\.[0-9]*$). Use for fractional rewardPoints comparisons.",
    "isoDate": "Absolute date in YYYY-MM-DD form. Compare with scheduleDate, dueDate, etc.",
    "futureDate": "Relative future date (e.g. 5d, 1w, 2m, 1y). Compare with scheduleDate, dueDate.",
    "pastDate": "Relative past date (e.g. -2m, -5d). Compare with scheduleDate, dueDate.",
    "title": "Title search (case-insensitive); syntax title:word or title:\"multi word\".",
    "Title": "Title search (case-sensitive); syntax Title:Word.",
    "title0": "Title starts-with search (case-insensitive); syntax title0:word.",
    "Title0": "Title starts-with search (case-sensitive); syntax Title0:Word.",
    "note": "Note-text search (case-insensitive); syntax note:word.",
    "Note": "Note-text search (case-sensitive); syntax Note:Word.",
    "timeEstimateSum": "Duration estimate query, e.g. <~5m, ~0, <=~1h, >~30s. Σ prefix uses computed (summed) duration.",
    "category": "Category/project reference; syntax #CategoryName or #\"Category Name\".",
    "goal": "Goal reference; syntax ##GoalName or ##\"Goal Name\".",
    "section": "Section reference; syntax !SectionName or !\"Section Name\".",
}

# Operator vocabulary for the {op, val} clauses on individual SmartLists fields
# (the UI-driven structure stored in CouchDB, distinct from the advanced DSL).
# Each inner dict maps op string to its UI meaning.
PER_FIELD_OPS: dict[str, dict[str, str]] = {
    "backburner": {
        "any": "unspecified",
        "n": "not on backburner",
        "y": "on backburner",
    },
    "created": {
        "any": "unspecified",
        "<": "more than...",
        "=": "exactly...",
        ">": "less than...",
    },
    "day": {
        "any": "unspecified",
        "0": "unscheduled",
        "<": "before...",
        "=": "exactly...",
        ">": "after...",
    },
    "firstScheduled": {
        "any": "unspecified",
        "unassigned": "never scheduled",
        "1": "previously scheduled",
    },
    "goalId": {
        "any": "unspecified",
        "inAny": "in any goal",
        "none": "not in a goal",
        "in": "in goal...",
        "nin": "not in goal...",
    },
    "hasTime": {
        "any": "unspecified",
        "y": "has time",
        "n": "without time",
    },
    "isPinned": {
        "any": "unspecified",
        "y": "pinned",
        "n": "not pinned",
    },
    "itemType": {
        "any": "tasks and projects",
        "task": "tasks",
        "taskNotInProject": "single tasks (not in a project)",
        "singles": "single tasks & projects",
        "project": "projects",
        "subproject": "subprojects",
        "notSubproject": "projects (not subprojects)",
    },
    "labelIds": {
        "any": "unspecified",
        "0": "with no labels",
        "1": "with any label",
        "in": "with label...",
        "nin": "without label...",
    },
    "nextStep": {
        "any": "unspecified",
        "is": "next step",
    },
    "orbit": {
        "any": "unspecified",
        "n": "not in orbit",
        "y": "in orbit",
    },
    "parentId": {
        "any": "unspecified",
        "in": "in...",
        "nin": "not in...",
    },
    "planAhead": {
        "any": "unspecified",
        "&unplanned": "not planned",
        "&thisWeek": "planned this week",
        "&nextWeek": "planned next week",
        "&lastWeek": "planned last week",
        "&thisMonth": "planned this month",
        "&nextMonth": "planned next month",
        "&lastMonth": "planned last month",
        "&": "planned...",
    },
    "procrastinationCount": {
        "any": "unspecified",
        ">": "more than...",
        "=": "exactly...",
        "<": "less than...",
    },
    "recurring": {
        "any": "Any",
        "n": "non-recurring",
        "rt": "recurring tasks",
        "rp": "recurring projects",
        "y": "any recurring",
    },
    "timeBlock": {
        "any": "unspecified",
        "now": "in current time block",
    },
    "timeEstimate": {
        "any": "unspecified",
        "0": "no duration",
        "<": "shorter than...",
        "<=": "shorter than or equal to...",
        "=": "exactly...",
        ">": "longer than...",
        ">=": "longer than or equal to...",
        "between": "between...",
    },
    "title": {
        "any": "unspecified",
        "in": "contains...",
        "=": "is...",
    },
}
