"""Filter DSL reference for Amazing Marvin SmartLists.

Mirrors the predicate, operator, and token vocabulary used by Marvin's
advanced filter engine. The Marvin help center documents a subset:
https://help.amazingmarvin.com/en/articles/2070779-advanced-smart-list-filters

Used by the SmartLists schema in doc_types.py to give MCP callers a complete
operator inventory when reading or writing smart-list filter expressions.

Aliases: predicates carrying a ``*`` prefix in user-facing syntax (e.g.
``*backburner``, ``*new``, ``*stale``, ``*review``, ``*reward``,
``*hasSubtasks``, ``*hasOpenSubtasks``, ``*minutesTracked``, ``*rewardPoints``,
``*viaEmail``, ``*inGoal``) are accepted with or without the prefix. Where a
predicate has alternative spellings (e.g. ``*"red star"`` or ``*a`` for
``p1``), its help text ends with an ``Aliases:`` list.

The ``&`` prefix is not an alias but part of the name: those predicates test
Plan Ahead membership (week, month or quarter). Where their help text mentions
values "derived from" a shorter period, that derivation is on unless
``strategySettings.planAhead.upwardPlanningSync`` is set to false.
"""

# Predicates from the advanced filter DSL. Mix of boolean tests (return
# True/False), comparable fields (return numeric/date values), and date
# keywords (return absolute or relative dates). Sorted alphabetically.
PREDICATES: dict[str, str] = {
    "&inFuture": "True if this task/project is planned in the future.",
    "&inPast": "True if this task/project is planned in the past.",
    "&lastMonth": "True if this task/project is planned last month (including derived from week if sync enabled).",
    "&lastQuarter": "True if this task/project is planned for last quarter (including derived from month/week if sync enabled).",
    "&lastWeek": 'True if this task/project is planned last week. Planned weeks are always stored as their Monday, but which week counts as "last" follows your week start setting.',
    "&monthPlanned": "True if this task/project is month planned (including derived from week if sync enabled).",
    "&nextMonth": "True if this task/project is planned next month (including derived from week if sync enabled).",
    "&nextQuarter": "True if this task/project is planned for next quarter (including derived from month/week if sync enabled).",
    "&nextWeek": 'True if this task/project is planned for next week. Planned weeks are always stored as their Monday, but which week counts as "next" follows your week start setting.',
    "&planned": "True if this task/project is planned (for any time period: week, month, or quarter).",
    "&quarterPlanned": "True if this task/project is quarter planned (including derived from month/week if sync enabled).",
    "&thisMonth": "True if this task/project is planned this month (including derived from week if sync enabled).",
    "&thisQuarter": "True if this task/project is planned for this quarter (including derived from month/week if sync enabled).",
    "&thisWeek": 'True if this task/project is planned for this week. Planned weeks are always stored as their Monday, but which week counts as "this" one follows your week start setting.',
    "&unplanned": "True if this task/project is neither week planned nor month planned nor quarter planned.",
    "&weekPlanned": "True if this task/project is week planned.",
    "backburner": "True if this task/project is on the backburner.",
    "createdRecently": "True if this task/project was created in the last 7 days.",
    "createdThisWeek": "True if this task/project was created this week.",
    "createdToday": "True if this task/project was created today.",
    "creationDate": "The date when the task/project was created.",
    "d1": 'True if this task/project has dread level 1 - Baby Frog (I dread this a little). Aliases: *"I dread this a little", *"baby frog".',
    "d2": 'True if this task/project has dread level 2 - Frog (I dread this). Aliases: *"I dread this", *"frog".',
    "d3": 'True if this task/project has dread level 3 - Monster Frog (I dread this a ton). Aliases: *"I dread this a ton", *"high dread", *"monster frog".',
    "d4": 'True if this task/project has dread level 4 - Toxic Frog (This might kill me). Aliases: *"This might kill me", *"extreme dread", *"toxic frog".',
    "deadlineOverdue": "True if this task/project is past its deadline. Aliases: *overdue.",
    "done": "True if this task/project is marked as done. Aliases: *completed, *finished.",
    "doneDate": "The date when the task/project was marked as complete. Only works in Search, as completed items are not shown in Smart Lists.",
    "dueDate": "The task/project's due date. This includes inheritance.",
    "dueIn3Days": "True if this task/project is due within the next 3 days.",
    "dueIn7Days": "True if this task/project is due within the next 7 days.",
    "dueThisWeek": "True if this task/project is due this week.",
    "dueToday": "True if this task/project is due today.",
    "dueTomorrow": "True if this task/project is due tomorrow.",
    "e1": 'True if this task/project requires low focus. Aliases: *"low focus".',
    "e2": 'True if this task/project requires high focus. Aliases: *"high focus", *focus.',
    "e3": 'True if this task/project requires low energy. Aliases: *"low energy".',
    "e4": 'True if this task/project requires high energy. Aliases: *"high energy".',
    "e5": "True if this task/project requires physical activity. Aliases: *physical.",
    "endDate": "The task/project's end date.",
    "endOfMonth": "The date of the last day of this month.",
    "endOfWeek": "The date of the end of the work week. This respects your work week settings.",
    "energyLevel": "True if this task/project has any energy level set. Aliases: *hasEnergy.",
    "f1": 'True if this is a baby frog task/project. Aliases: *"baby frog".',
    "f2": "True if this is a regular frog task/project. Aliases: *frog.",
    "f3": 'True if this is a monster frog task/project. Aliases: *"monster frog".',
    "f4": 'True if this is a toxic frog task/project. Aliases: *"toxic frog".',
    "firstScheduled": "The task/project's first schedule date. This tells you whether it has been delayed, and by how long.",
    "fromPinned": "True if this task was created from a pinned task.",
    "hasBeenScheduled": "True if this task/project was scheduled in the past, or false if it's never been scheduled. If it was scheduled in the past, it has been delayed at least once.",
    "hasChildren": "True if this project has open tasks or subprojects.",
    "hasDeadline": "True if this task/project has a deadline (due date). Aliases: *hasDueDate.",
    "hasDependants": "True if this task/project is a dependency of an open task/project.",
    "hasEnergy": "True if this task/project has an energy type set.",
    "hasGoal": "True if this task/project is linked to a goal.",
    "hasNote": "True if this task/project has a note.",
    "hasOpenSubtasks": "Matches Tasks that have open Subtasks.",
    "hasPledge": "True if this task/project has a pledge date.",
    "hasPositivity": "True if this task/project has any positive energy. Aliases: *isPositive.",
    "hasReminder": "True if the task has a reminder time in the future.",
    "hasReviewDate": "True if this task/project has a review date.",
    "hasStartDate": "True if this task/project has a start date.",
    "hasSubtasks": "Matches Tasks that have Subtasks.",
    "hasTime": "True if this task/project has a time in its title (using any time format, like 7am or 19:00).",
    "hasTimeEstimate": 'True if this task/project has a duration set. Aliases: *"has estimate", *"has time estimate", *"has duration".',
    "hasWeight": "True if this task/project has any mental weight. Aliases: *isWeighing.",
    "inCurrentTimeBlock": "True if this task/project matches the current time block's linked smart list.",
    "inFroggedProject": "True if this task is in a frogged/dreaded project.",
    "inGoal": "Matches Tasks/Projects that are in any Goal.",
    "inheritedScheduleDate": "The task/project's inherited schedule date. This is the minimum of the schedule dates of the item and its ancestors, or null if none are scheduled.",
    "inImportantProject": "True if this task is in a starred/important project.",
    "inMIPProject": "True if this task is in a Most Important Project.",
    "isArchived": "True if this task/project is archived, or inside an archived category.",
    "isCalDAVSynced": "True if this task is synced to a CalDAV provider.",
    "isCalendarSynced": "True if this task is synced to a calendar.",
    "isCategory": "True if this is a category (not a project or task).",
    "isDependent": "True if this task/project is dependent on an open task/project.",
    "isFirstStep": "True if this task is the first step of a project.",
    "isFirstUnscheduled": "True if this task is the first unscheduled task in a project.",
    "isFrogged": "True if this is a task/project has any kind of frog/dread. Aliases: hasDread, dread.",
    "isGoogleSynced": "True if this task is synced to a google calendar.",
    "isHabit": 'True if this is a habit, or a habit shown as a task in the day list. Aliases: *habit, *"is habit".',
    "isIcloudSynced": "True if this task is synced to an iCloud calendar.",
    "isMIP": "True if this project is one of your Most Important Projects.",
    "isNextStep": "True if this task is the next step of a project.",
    "isOutlookSynced": "True if this task is synced to an outlook calendar.",
    "isParallel": "Matches non-sequential projects.",
    "isPinned": "True if this task is itself pinned (i.e. the pinned task parent that lives in the Master List).",
    "isPledged": "True if this task/project has a future scheduleDate.",
    "isProject": 'True if this item is a project. Aliases: *project, *"is project".',
    "isRecurring": "True if this task/project was created from a recurring item.",
    "isScheduled": "True if this task/project is currently scheduled.",
    "isSequential": "Matches sequential projects.",
    "isShared": "True if this task is in a shared list.",
    "isSnoozed": "True if this task/project has been snoozed.",
    "isStarred": "True if this has importance (any star). Does NOT include low priority (down arrow).",
    "isTask": 'True if this item is a task (not a project, category or habit). Aliases: *task, *"is task".',
    "isTracked": "True if this task has been time tracked.",
    "isTracking": "Experimental. True if the task is being tracked.",
    "isUnscheduled": "True if the task/project isn't scheduled, else false if is.",
    "isUrgent": "True if this task/project has any urgency level.",
    "isWorkSession": "Matches Work Session tasks.",
    "isYahooSynced": "True if this task is synced to a yahoo calendar.",
    "justStarted": "True if this item left the backburner due to its start date and you haven't yet acknowledged it, or false otherwise (i.e. it wasn't just started or you already acknowledged it).",
    "longTask": "True if this task/project has a duration over 1 hour.",
    "lowPriority": 'True if this task/project is marked as low priority (down arrow). Aliases: *"low priority".',
    "mentalWeight": "True if this task/project has any mental weight. Aliases: *hasWeight.",
    "minutesTracked": "The number of minutes tracked on this task, else 0.",
    "mip": "True if this is a MIP project.",
    "missingNextStep": "True if this project doesn't have any next steps (i.e. open tasks).",
    "neverProcrastinated": "True if this task/project has never been rescheduled.",
    "neverScheduled": "True if this task/project has never been scheduled.",
    "new": "True if this task/project is newly available for working on (due to dependencies, start date, or newly created recurring projects).",
    "noDeadline": "True if this task/project does not have a deadline. Aliases: *noDueDate.",
    "noEnergy": 'True if this task/project has no energy level set (no focus, energy, or physical). Aliases: *"no energy level".',
    "noFrog": 'True if this task/project has no frog/dread set. Aliases: *"no frog", *"no dread".',
    "noGoal": "True if this task/project is not linked to a goal.",
    "noPledge": "True if this task/project does not have a pledge date.",
    "noPositivity": 'True if this task/project has no positive energy set. Aliases: *"no positivity".',
    "noPriority": 'True if this task/project has no importance set (not starred, not low priority). Aliases: *"no priority", *"regular", *"no importance".',
    "noReviewDate": "True if this task/project does not have a review date.",
    "noSize": 'True if this task/project has no size set. Aliases: *"no size".',
    "noStartDate": "True if this task/project does not have a start date.",
    "noTimeEstimate": "True if this task/project does not have a duration.",
    "notStarted": "True if this task/project has a future start date.",
    "noUrgency": 'True if this task/project has no urgency set. Aliases: *"no urgency".',
    "now": "True if this task is scheduled for right now.",
    "noWeight": 'True if this task/project has no mental weight set. Aliases: *"no weight".',
    "numDoneTasks": "The number of completed tasks in this project, or null if it's a task.",
    "numLabels": "The number of labels this task/project has.",
    "numOpenSubtasks": "The number of open Subtasks a Task has.",
    "numOpenTasks": "The number of open tasks in this project, or null if it's a task.",
    "numScheduledTasks": "The number of scheduled open tasks in this project, or null if it's a task.",
    "numSubtasks": "The number of Subtasks a Task has (open and completed).",
    "numUnscheduledTasks": "The number of unscheduled open tasks in this project, or null if it's a task.",
    "orbit": "True if this task/project is in orbit.",
    "p1": 'True if this is a high priority (red star / most important) task/project. Aliases: *"red star", *a, *"most important".',
    "p2": 'True if this is a medium priority (orange star / very important) task/project. Aliases: *"orange star", *b, *"very important".',
    "p3": 'True if this is a priority (yellow star / important) task/project. Aliases: *"yellow star", *c, *important.',
    "pickedProject": "True if this is a project that has been picked today using the Project Focus Picker, or false if it's not a project or hasn't been picked.",
    "plannedMonth": "The task/project's planned month. This is null if not planned.",
    "plannedQuarter": "The task/project's planned quarter, formatted YYYY-Q<n> (e.g. 2026-Q3). This is null if not planned.",
    "plannedWeek": "The task/project's planned week. This is actually the date of the first day of that week, or null if not planned.",
    "pledgeDate": "The task/project's accountability pledge date.",
    "pledgeDue1Day": "True if this task/project has a pledge due tomorrow.",
    "pledgeDue3Days": "True if this task/project has a pledge due within 3 days.",
    "pledgeDue7Days": "True if this task/project has a pledge due within 7 days.",
    "pledgeDueToday": "True if this task/project has a pledge due today.",
    "pos1": "True if you're curious about this task/project. Aliases: *curious, *\"I'm curious about this\".",
    "pos2": "True if you're excited about this task/project. Aliases: *excited, *\"I'm excited about this\".",
    "pos3": 'True if you like doing this task/project. Aliases: *joy, *"I like doing this", *"I like this".',
    "pos4": 'True if you love doing this task/project. Aliases: *passionate, *"I love doing this", *"I love this".',
    "positiveEnergy": "True if this task/project has any positive energy. Aliases: *hasPositivity.",
    "previouslyScheduled": "True if this task/project was scheduled in the past.",
    "procrastinated": "True if this task/project has been rescheduled (delayed).",
    "procrastinationCount": "The number of days this task/project has been delayed (carried forward from the day it was first scheduled).",
    "quickTask": "True if this task/project has a duration under 15 minutes.",
    "review": "True if it's time to review this task/project.",
    "reviewDate": "The task/project's review date.",
    "reviewIn3Days": "True if this task/project is due for review within the next 3 days.",
    "reviewIn7Days": "True if this task/project is due for review within the next 7 days.",
    "reviewOverdue": "True if this task/project is past its review date.",
    "reviewThisWeek": "True if this task/project is due for review this week.",
    "reviewToday": "True if this task/project is due for review today.",
    "reviewTomorrow": "True if this task/project is due for review tomorrow.",
    "reward": "True if this is a reward task (from the Reward Tasks strategy). Note: this is not the same as having an attached reward (from the Rewards strategy).",
    "rewardPoints": "The number of reward points this task/project has been directly assigned (not including defaults!).",
    "scheduleDate": "The task/project's schedule date. This does not include inheritance! So if a task is not scheduled, but its parent project is, this is null instead.",
    "scheduleDatePlain": "The task/project's schedule date ignoring rollover, auto-schedule due tasks, and inheritance.",
    "scheduleWeek": "The week when the task/project is scheduled onto the stack. This is actually the date of the first day of that week, or null if unscheduled.",
    "selectedDate": "The main view's selected date. This is the date that is shown in the sidebar, not today. You can change it using arrow keys (or buttons in the sidebar) to look at your schedule in the future/past in My Day.",
    "selectedMonth": "The main view's selected date's month. Useful e.g. for comparing with &plannedMonth.",
    "selectedWeek": "The main view's selected date's start of week date. Useful e.g. for comparing with &plannedWeek. Warning: Monday is considered the start of the week here!",
    "sizeL": "True if this task/project is size L (large).",
    "sizeM": "True if this task/project is size M (medium).",
    "sizeS": "True if this task/project is size S (small).",
    "sizeXL": "True if this task/project is size XL (extra large).",
    "sizeXS": "True if this task/project is size XS (extra small).",
    "stale": "True if this task/project matches your Staleness Warning conditions.",
    "startDate": "The task/project's start date.",
    "started": "True if this task/project has a start date in the past.",
    "startOfISOWeek": "The date of the start of the work week. This uses Monday as the week start and doesn't respect your work week settings. This can be helpful for working with *plannedWeek since planned weeks in Marvin are always based on ISO weeks.",
    "startOfMonth": "The date of the 1st day of this month.",
    "startOfWeek": "The date of the start of the work week. This respects your work week settings.",
    "startsIn3Days": "True if this task/project starts within the next 3 days.",
    "startsIn7Days": "True if this task/project starts within the next 7 days.",
    "startsThisWeek": "True if this task/project starts this week.",
    "startsToday": "True if this task/project starts today.",
    "startsTomorrow": "True if this task/project starts tomorrow.",
    "taskSize": "True if this task/project has any size set. Aliases: *hasSize.",
    "time": "The task/project's time (extracted from its title). Useful for comparing with a fixed time.",
    "today": "Today's date.",
    "tomorrow": "Tomorrow's date.",
    "u1": 'True if this task/project is marked as somewhat urgent (level 1). Aliases: *"somewhat urgent".',
    "u2": "True if this task/project is marked as urgent (level 2). Aliases: *urgent.",
    "u3": 'True if this task/project is marked as very urgent (level 3). Aliases: *"very urgent".',
    "u4": 'True if this task/project is marked as extremely urgent (level 4). Aliases: *"extremely urgent", *"on fire".',
    "updateDate": "The date when the task/project was last updated, or its creation date if it was never updated. This means you can use \"creationDate updateDate ==\" to find items that haven't been updated since their creation.",
    "viaEmail": "Matches Tasks that were created by email.",
    "w1": "True if this task/project is weighing on your mind a little (level 1). Aliases: *weight, *weighing.",
    "w2": "True if this task/project is heavy on your mind (level 2). Aliases: *heavy.",
    "w3": 'True if this task/project is very heavy on your mind (level 3). Aliases: *"super weight", *"very heavy".',
    "w4": "True if this task/project has crushing weight (level 4). Aliases: *overwhelming.",
    "workedOnDate": "The date when the task/project was last worked on. This includes time tracking and completion of subtasks, but not simple edits. If the item has never been worked on, then this is the same as the creationDate. So you can use \"workedOnDate creationDate ==\" to see items that haven't been worked on.",
    "workTomorrow": "Tomorrow's date, but skipping weekends. So today is Friday and your weekends are Saturday+Sunday, this is Monday's date. This respects your work week settings.",
    "yesterday": "Yesterday's date.",
}

# Functions accepting a sub-expression as their argument.
FUNCTIONS: dict[str, str] = {
    "parent": "Match items whose parent matches the given expression. e.g. parent(*isStarred type:project &&) matches tasks inside starred projects.",
    "anyAncestor": "Match items where any ancestor (parent, grandparent, ...) matches the expression.",
    "anyChild": "Match items that have at least one child matching the expression.",
    "allChildren": "Match items where every child matches the expression.",
    "anySibling": "Match items where any sibling matches the expression.",
    "allSiblings": "Match items where every sibling matches the expression.",
}

# Postfix (RPN) operators. Operands appear before the operator.
OPERATORS: dict[str, str] = {
    "||": "OR (logical disjunction).",
    "&&": "AND (logical conjunction).",
    "!": "NOT (unary negation).",
    "==": "Equality.",
    "!=": "Inequality.",
    ">": "Greater than.",
    "<": "Less than.",
    ">=": "Greater than or equal.",
    "<=": "Less than or equal.",
    "+": "Addition (arithmetic).",
    "-": "Subtraction (arithmetic).",
}

# Token types recognized by the DSL parser. Plus implicit prefix tokens:
# @label / @"label name" — label reference;
# `type:task|project|category` — type filter.
# (Backticks are load-bearing: a comment starting with `# type:` is read as a
# PEP 484 type comment and fails to parse.)
TOKENS: dict[str, str] = {
    "number": "Integer literal (regex: ^[0-9]+$). Use for comparing rewardPoints, numScheduledTasks, etc.",
    "float": "Decimal literal (regex: ^[0-9]+\\.[0-9]*$). Use for fractional rewardPoints comparisons.",
    "isoDate": "Absolute date in YYYY-MM-DD form. Compare with scheduleDate, dueDate, etc.",
    "futureDate": "Relative future date (e.g. 5d, 1w, 2m, 1y). Compare with scheduleDate, dueDate.",
    "pastDate": "Relative past date (e.g. -2m, -5d). Compare with scheduleDate, dueDate.",
    "title": 'Title search (case-insensitive); syntax title:word or title:"multi word".',
    "Title": "Title search (case-sensitive); syntax Title:Word.",
    "title0": "Title starts-with search (case-insensitive); syntax title0:word.",
    "Title0": "Title starts-with search (case-sensitive); syntax Title0:Word.",
    "note": "Note-text search (case-insensitive); syntax note:word.",
    "Note": "Note-text search (case-sensitive); syntax Note:Word.",
    "timeEstimateSum": "Duration estimate query, e.g. <~5m, ~0, <=~1h, >~30s. Σ prefix uses computed (summed) duration.",
    "category": 'Category/project reference; syntax #CategoryName or #"Category Name".',
    "goal": 'Goal reference; syntax ##GoalName or ##"Goal Name".',
    "section": 'Section reference; syntax !SectionName or !"Section Name".',
}

# Operator vocabulary for the {op, val} clauses on individual SmartLists fields
# (the UI-driven structure stored in CouchDB, distinct from the advanced DSL).
# Each inner dict maps op string to its UI meaning.
PER_FIELD_OPS: dict[str, dict[str, str]] = {
    "backburner": {
        "any": "unspecified",
        "n": "not on backburner",
        "y": "on backburner",
    },
    "created": {
        "any": "unspecified",
        "<": "more than...",
        "=": "exactly...",
        ">": "less than...",
    },
    "day": {
        "any": "unspecified",
        "0": "unscheduled",
        "<": "before...",
        "=": "exactly...",
        ">": "after...",
    },
    "firstScheduled": {
        "any": "unspecified",
        "unassigned": "never scheduled",
        "1": "previously scheduled",
    },
    "goalId": {
        "any": "unspecified",
        "inAny": "in any goal",
        "none": "not in a goal",
        "in": "in goal...",
        "nin": "not in goal...",
    },
    "hasTime": {
        "any": "unspecified",
        "y": "has time",
        "n": "without time",
    },
    "isPinned": {
        "any": "unspecified",
        "y": "pinned",
        "n": "not pinned",
    },
    "itemType": {
        "any": "tasks and projects",
        "task": "tasks",
        "taskNotInProject": "single tasks (not in a project)",
        "singles": "single tasks & projects",
        "project": "projects",
        "subproject": "subprojects",
        "notSubproject": "projects (not subprojects)",
    },
    "labelIds": {
        "any": "unspecified",
        "0": "with no labels",
        "1": "with any label",
        "in": "with label...",
        "nin": "without label...",
    },
    "nextStep": {
        "any": "unspecified",
        "is": "next step",
    },
    "orbit": {
        "any": "unspecified",
        "n": "not in orbit",
        "y": "in orbit",
    },
    "parentId": {
        "any": "unspecified",
        "in": "in...",
        "nin": "not in...",
    },
    "planAhead": {
        "any": "unspecified",
        "&unplanned": "not planned",
        "&thisWeek": "planned this week",
        "&nextWeek": "planned next week",
        "&lastWeek": "planned last week",
        "&thisMonth": "planned this month",
        "&nextMonth": "planned next month",
        "&lastMonth": "planned last month",
        "&": "planned...",
    },
    "procrastinationCount": {
        "any": "unspecified",
        ">": "more than...",
        "=": "exactly...",
        "<": "less than...",
    },
    "recurring": {
        "any": "Any",
        "n": "non-recurring",
        "rt": "recurring tasks",
        "rp": "recurring projects",
        "y": "any recurring",
    },
    "timeBlock": {
        "any": "unspecified",
        "now": "in current time block",
    },
    "timeEstimate": {
        "any": "unspecified",
        "0": "no duration",
        "<": "shorter than...",
        "<=": "shorter than or equal to...",
        "=": "exactly...",
        ">": "longer than...",
        ">=": "longer than or equal to...",
        "between": "between...",
    },
    "title": {
        "any": "unspecified",
        "in": "contains...",
        "=": "is...",
    },
}
